#!/bin/sh

case "$1" in
    deconfig)
        ip addr flush dev $interface
        ip link set $interface up
        ;;
    bound|renew)
        ip addr add $ip/$mask dev $interface

        [ -n "$router" ] && ip route add default via $router dev $interface

        [ -n "$dns" ] && {
            echo -n > /etc/resolv.conf
            for i in $dns; do
                echo "nameserver $i" >> /etc/resolv.conf
            done
        }
        ;;
esac

exit 0
